repos:
  - repo: local
    hooks:
      - id: swift-test
        name: Swift Tests  
        entry: bash -c 'timeout 120s swift test --parallel || echo "Tests skipped (timeout or failed)"'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: swiftlint
        name: SwiftLint
        entry: velo exec swiftlint --fix --quiet
        language: system
        files: \.swift$
        stages: [pre-commit]
        
      - id: architecture-check
        name: Architecture Check
        entry: |
          bash -c 'if [[ "$(uname -m)" != "arm64" ]]; then echo "Error: This project requires Apple Silicon (arm64)"; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: performance-check
        name: Performance Regression Check
        entry: bash -c 'timeout 60s swift test --filter testPerformanceRegression || echo "Performance check skipped (timeout or failed)"'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        
      - id: memory-check
        name: Memory Leak Check
        entry: leaks --atExit -- swift test
        language: system
        pass_filenames: false
        stages: [pre-push]
        
