// This file is automatically generated by Scripts/generate-version.sh
// DO NOT EDIT MANUALLY - it will be overwritten on every build

import Foundation

/// Build-time generated version information
/// This file is created during compilation and contains version info from Git
public struct GeneratedVersion {

    /// The version string (SemVer compliant)
    public static let version = "0.0.2"

    /// Build timestamp (ISO 8601 UTC)
    public static let buildDate = "2025-07-04T20:45:54Z"

    /// Git commit hash (short)
    public static let gitCommit = "fcf569f"

    /// Git commit hash (full)
    public static let gitCommitFull = "fcf569f69a5bc98a372a6bce4f7707e72f132680"

    /// Git tag (if any)
    public static let gitTag = "v0.0.2"

    /// Whether the working directory was dirty at build time
    public static let isDirty = true

    /// Whether the build was made exactly on a Git tag
    public static let isOnTag = true

    /// Build information summary
    public static let buildInfo: String = {
        var info = "Built on \(buildDate)"
        if !gitCommit.isEmpty && gitCommit != "unknown" {
            info += " from commit \(gitCommit)"
        }
        if !gitTag.isEmpty {
            info += " (tag: \(gitTag))"
        }
        if isDirty {
            info += " with uncommitted changes"
        }
        return info
    }()
}
