name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v0.1.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Get version
        id: get_version
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build release binary
        run: |
          ./Scripts/build.sh --release --arch arm64
          
      - name: Create release directory
        run: |
          mkdir -p release
          cp .build/release/velo release/velo
          chmod +x release/velo
          
      - name: Create tarball
        run: |
          cd release
          tar -czf velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz velo
          
      - name: Generate SHA256 checksum
        run: |
          cd release
          shasum -a 256 velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz > velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz.sha256
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Release ${{ steps.get_version.outputs.VERSION }}
            
            ## Installation via Homebrew
            ```bash
            brew install dimaosipa/brew/velo
            ```
            
            ## Manual Installation
            Download the binary and extract:
            ```bash
            wget https://github.com/dimaosipa/velocity/releases/download/${{ steps.get_version.outputs.VERSION }}/velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz
            tar -xzf velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz
            ./velo install-self
            ```
            
            ## Requirements
            - macOS 12.0 or later
            - Apple Silicon (M1/M2/M3) Mac
            
          files: |
            release/velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz
            release/velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update Homebrew Tap
        uses: ./.github/actions/update-homebrew-tap
        with:
          formula-name: velo
          homebrew-tap: dimaosipa/brew
          formula-path: Formula/velo.rb
          download-url: https://github.com/dimaosipa/velocity/releases/download/${{ steps.get_version.outputs.VERSION }}/velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz
          version: ${{ steps.get_version.outputs.VERSION }}
          sha256-file: release/velo-${{ steps.get_version.outputs.VERSION }}-arm64.tar.gz.sha256
          commit-message: |
            velo ${{ steps.get_version.outputs.VERSION }}
            
            Automated update from dimaosipa/velocity release
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}